#!/usr/bin/env zsh

# From https://github.com/ThePrimeagen/.dotfiles/blob/e2a01c86e98c54992ca75e8e8d56083df35b0578/clean-env
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
