#!/usr/bin/env zsh

# From https://github.com/ThePrimeagen/.dotfiles/blob/e2a01c86e98c54992ca75e8e8d56083df35b0578/install
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,alacritty,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Adding $folder"
    stow $folder
done
