alias starwars='telnet towel.blinkenlights.nl'
alias stat='git status'
alias add='git add .'
alias commit='git commit -m'
alias push='git push'
alias branch='git branch'
alias logp='git log --pretty=oneline'
alias gvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
alias contest='cd ~/Dropbox/CSCI\ 491\ -\ Programming\ Contest\ Problem\ Solving'
alias cl='clear'
alias ll='ls -al'
alias e='vi'
alias soci='cd ~/Dropbox/SOCI\ 101\ Into\ to\ Sociology/Lecture_notes'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
