alias starwars='telnet towel.blinkenlights.nl'
alias stat='git status'
alias add='git add .'
alias commit='git commit -m'
alias push='git push'
alias branch='git branch'
alias log='git log --pretty=oneline'
alias logp='git log --graph --abbrev-commit --decorate --date=relative --all'
alias gvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
alias cl='clear'
alias ll='ls -Shal'
alias e='vi'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

